---
title: "Final Attributes"
author: "Anna Talucci"
date: "2024-03-27"
output: html_document
---

# clear environment
```{r}
rm(list=ls())
```

# Overview
Finalize datacube attributes


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(ggpubr)
library(ggnewscale)
library(ggthemes)
```


# Data

## Predicted measurements
```{r}
datacubePred = read_csv("../data/dataCube/DatacubePermafrostFirePredicted.csv")
```

```{r}
datacubePred
```


```{r}
names(datacubePred)
```

```{r}
( rocha = datacubePred %>% filter(submitNm=="Rocha") )
rocha %>% filter(siteId=="Anaktuvuk River fire")
unique(rocha$fireYr)
```

# Final clean up
```{r}
datacubePred$fireYr[datacubePred$siteId == "Anaktuvuk River fire"] <- 2007
datacubePred$distur[datacubePred$siteId == "lutose_unburn"] <- "unburned"
```

# Add Time since fire 

```{r}
( datacubePred1 = datacubePred %>% 
  dplyr::select(plotId:resRealm, permaCombo:permaRelict, predDoy, predDepth) %>% 
  mutate(tsf = year-fireYr)
)

```

```{r}
datacubePred1$tsf[datacubePred1$distur == "unburned"] <- "NA"

```


```{r}
unique(datacubePred1$tsf)
```


```{r}
( datacubePred2 = datacubePred1 %>% filter(tsf !=("12013")) )
```

```{r}
write_csv(datacubePred2, '../outputs/dataCube/PermafrostFireDatacubeFinal.csv')
```

# Summary information

```{r}
unique(sort(datacubePred2$fireYr))
```
```{r}
unique(sort(datacubePred2$siteId))
```

```{r}
unique(sort(datacubePred2$resName))
```
```{r}
unique(sort(datacubePred2$submitNm))
```

```{r}
unique(sort(datacubePred2$cntryId))
```

```{r}
unique(sort(datacubePred2$resBiomeNm))
```
```{r}
datacubePred2 %>% group_by(cntryId) %>% summarise(n=n())
```

```{r}
datacubePred2 %>% group_by(permaExtent) %>% summarise(n=n())
```
```{r}
datacubePred2 %>% group_by(resBiomeNm) %>% summarise(n=n())
```

# Repeat measures

```{r}
names(datacubePred1)
```

```{r}
datacubePred1 %>% group_by(submitNm, siteId, paired, fireYr, year) %>% summarize(n = n())
```

```{r}
(repeatMeasures = datacubePred1 %>% group_by(submitNm, siteId, paired, fireYr) %>% summarize(numberYrsMeasured = n_distinct(year)) %>% filter(fireYr!=-9999) %>% filter(numberYrsMeasured>1) )
```

```{r}
unique(repeatMeasures$paired)
```

```{r}
write_csv(repeatMeasures, '../outputs/RepeatMeasuresFromDataCube.csv')
```

```{r}
datacubePred1 %>% group_by(submitNm, fireYr, year) %>% summarize(n = n())
```

```{r}
datacubePred1 %>% filter(submitNm=="Buma") %>% filter(siteId %in% c('STEESE_1','STEESE_2', 'STEESE_3'))
```















